- name: Update apt sources
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: yes

- name: Upgrade all apt packages
  apt:
    upgrade: full
  when: ansible_facts['distribution'] == "Ubuntu"
  become: yes

- name: Check if a reboot is needed
  stat:
    path: /var/run/reboot-required
    get_checksum: no
    get_attributes: no
    get_mime: no
  register: reboot_required_file
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Reboot the system if necessary
  reboot:
  when: reboot_required_file.stat.exists
  become: yes
