- name: Update apt sources
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Upgrade all apt packages
  apt:
    upgrade: full
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Check if a reboot is needed
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Reboot the system if necessary
  reboot:
  when: reboot_required_file.stat.exists
